name: CI

on: push

jobs:
  build-lambda:
    name: Build Project

    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build Project
        run: |
          npm ci
          npm run lint
          npm run test
          npm run build
